name: Deploy site

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Substituir variáveis
        run: |
          echo "Injetando link do grupo..."
          sed -i "s|__LINK_BOTAO__|${{ secrets.LINK_BOTOES }}|g" ./js/substitui-link-botoes.js

      - name: Deploy para o Pages
        uses: actions/upload-pages-artifact@v3

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/deploy-pages@v4
